### ISSUE TITLE
Type information lost for Pairs and Dicts with value type Any.

### ISSUE THREAD

**Issue by rasmushenningsson** [beacon-biosignals/StableHashTraits.jl#75]
I'm not sure whether this is to be considered a bug or just an edge case that we have to live with.
It's easy enough to work around with custom hash contexts when needed.
But I thought it might be worth an issue.

Setup:
```julia
using StableHashTraits
struct Foo x::Int end
struct Bar x::Int end
```

The following work as expected:
```julia-repl
julia> stable_hash(Foo(1); version=4) == stable_hash(Bar(1); version=4)
false

julia> stable_hash(Any[Foo(1)]; version=4) == stable_hash(Any[Bar(1)]; version=4)
false

julia> stable_hash(Tuple{Any}[(Foo(1),)]; version=4) == stable_hash(Tuple{Any}[(Bar(1),)]; version=4)
false
```

But for `Pair`s and `Dict`s with `eltype` `Any`, the distinction between `Foo` and `Bar` is lost:
```julia-repl
julia> stable_hash(Dict{Symbol,Any}(:a=>Foo(1)); version=4) == stable_hash(Dict{Symbol,Any}(:a=>Bar(1)); version=4)
true

julia> stable_hash(Pair{Symbol,Any}(:a,Foo(1)); version=4) == stable_hash(Pair{Symbol,Any}(:a,Bar(1)); version=4)
true

julia> stable_hash(Pair{Symbol,Any}[:a=>Foo(1)]; version=4) == stable_hash(Pair{Symbol,Any}[:a=>Bar(1)]; version=4)
true
```
NB: The last two require #74 to run.

It boils down to `hash_elements` where `isconcretetype(Pair{Symbol,Any})` returns true. Since `hoist_type` is also true, it skips type information for the elements.

**Comment by rasmushenningsson** [comment]
Here's a similar case with `Vector`s only.
I personally think this is less of a problem, but I wanted to show it for completeness.

```julia-repl
julia> stable_hash([Int[1]]; version=4) == stable_hash([Any[1]]; version=4)
false

julia> stable_hash(Vector{Any}[Int[1]]; version=4) == stable_hash(Vector{Any}[Any[1]]; version=4)
true
```

Again the problem is that `isconcretetype(Vector{Any})` returns true.

**Comment by ericphanson** [comment]
hm, to me it sounds like `hoist_type` is auto-enabled too often when it is not "safe" to do so

**Comment by haberdashPI** [comment]
Oooh... yeah this is a little tricky. I want to think through these examples a little bit (but have some other pressing stuff to focus on at the moment).

I think the solution is to do something like this:

```
function transformer(::Type{<:Pair{K,Y}}, ::HashVersion{4}) where {K,Y}
    return Transformer(((a, b),) -> Tuple{K,Y}(a, b); hoist_type=true)
end
```

To maintain the abstract nature of the contained types (to avoid excess type-hoisting). I haven' though the second, array example yet, but I'm guessing it's a similar problem.

**Comment by haberdashPI** [comment]
Having sat on this a bit and reviewed the different pieces of code, I actually think the right thing to target is not `hoist_type` but `isconcretetype`, as you originally posited @rasmushenningsson. This can happen even for types with a `identity` transform (such as the `Vector{Any}` example above). 

The type hoisiting is ultimatley assuming that the contained type of a concrete type are themselves concrete, so the logic can't use `isconcretetype`, it needs a new method (`is_fully_concrete`??) that recursively verifies the concrete nature of both the current type and its contained type (where contained is defined by what `StructType` it is).

**Comment by ericphanson** [comment]
how slow is it if we just drop all the hoisting stuff? (maybe with a cache?)

**Comment by rasmushenningsson** [comment]
Something like this?
```julia
is_fully_concrete(x) = true # handles type parameters that are not types, e.g. dimensions
function is_fully_concrete(::Type{T}) where {T}
	if T isa Union
		return is_fully_concrete(T.a) && is_fully_concrete(T.b)
	end
	isconcretetype(T) || return false
	for S in T.parameters
		is_fully_concrete(S) || return false
	end
	return true
end
```

It might also slow things down for complicated types with layers of nested type parameters.

**Comment by haberdashPI** [comment]
In essence, yes! Though there are a number of details I expect to be different. We have been avoiding `T.parameters` since it is not documented as public, and there are a few places I have seen it recommended against. The goal is to avoid anything like which could change in future julia versions. Instead I would use `StructType` and the public facing operations of `eltype` and `fieldtypes` to extract relevant type parameters. (We don't care about type parameters that aren't concrete if they don't correspond to fields or the eltype ).

But yes, this could slow down things for complicated types. At some point it might be good to add some benchmarks for deeply nested structures.

**Comment by haberdashPI** [comment]
If it was worth the lift, caching would easily turn that into a O(N) operation (but it's not clear yet to me if that's the case).

**Comment by rasmushenningsson** [comment]
Benchmarking seems like the way to go.
There are a number of possible tweaks, e.g. `is_fully_concrete` could give up if the nesting is too deep.

**Comment by haberdashPI** [comment]
Oh... having thought through your vector example some more, I have realized something very silly:

```julia
ulia> x = Vector{Any}[Int[1]]
1-element Vector{Vector{Any}}:
 [1]

julia> x[1]
1-element Vector{Any}:
 1
```

So the reason the example leads to an equivalent hash is that the two values are the same.

**Comment by haberdashPI** [comment]
Oh wow... 🤯 

I had thoroughly confused myself. This stuff is pretty tricky to reason about. It turns out that another way to fix this problem is to revert the change in #74 and replace it with:

```julia
hash_trait(::Pair) = StructTypes.OrderedStruct()
```

Then the examples above work as expected.

The issue here is that, as @ericphanson correctly observed, it is not actually safe to set `hoist_type=true` when transforming `Pair` into a Tuple. The problem being that it makes existing values that were in a field of type `Any` fall into a field (of the `Tuple`) of their concrete type of the value in that field. Which is exactly the reason for writing e.g. `pick_fields` to avoid this in the case of generating `NamedTuple` values of structs.

As I was reasoning through my proposed fix and the use of `is_fully_concrete` I realized that the same logic occurs (via the use of `isconcretetype`) inside of nested calls to `hash_fields`, so then I was confused about why we needed `is_fully_concrete`.

Problems only show up when `hash_fields/elements` doesn't get to see the types as the originally exist in the container (e.g. when calling `transform`). 

So at the end of the day, the problem here is that the original method I wrote for `transformer(::Type{<:Pair})` was wrong, fixing that problem and providing `Pair` an appropriate `StructType` means we no longer see the problems above.

Please feel free to check my reasoning here, but I'm fairly certain at the moment that it isn't possible to construct a concrete type containing e.g. `Any` that will produce a hash collision. #77 has a working version with the above fix.

My plan is to sit on this a little bit longer, and try to think of some counter examples.

**Comment by haberdashPI** [comment]
@ericphanson If I recall correctly, adding hashing to the mix (without type hoisting) was about 3x faster, so still roughly 1000x slower than with type hoisting.

**Comment by rasmushenningsson** [comment]
I agree that it's tricky to reason about, and easy to go down the wrong rabbit hole. :smile: 

The fix to treat `Pair` as an `OrderedStruct` seems like the right one.

In the current version of PR #77  I still get a failure here:
```julia
julia> stable_hash(Vector{Any}[Int[1]]; version=4) == stable_hash(Vector{Any}[Any[1]]; version=4)
true
```
What's your take on that one?

**Comment by haberdashPI** [comment]
> What's your take on that one?

See my comment above 🙂 

> Oh... having thought through your vector example some more, I have realized something very silly:
> 
> ```julia
> ulia> x = Vector{Any}[Int[1]]
> 1-element Vector{Vector{Any}}:
>  [1]
> 
> julia> x[1]
> 1-element Vector{Any}:
>  1
> ```
> 
> So the reason the example leads to an equivalent hash is that the two values are the same.

**Comment by rasmushenningsson** [comment]
Ah, I should have seen that! Thanks for finding my mistake. :facepalm: 

I'll close this since the PR has been merged. Thanks for fixing this!
